export const MetroAreas = [
  {
    name: "United States of America",
    city: "null",
    state: "United States of America",
  },
  { name: "Birmingham, AL", city: "Birmingham", state: "Alabama" },
  { name: "Little Rock, AR", city: "Little Rock", state: "Arkansas" },
  { name: "Phoenix, AZ", city: "Phoenix", state: "Arizona" },
  { name: "Tucson, AZ", city: "Tucson", state: "Arizona" },
  { name: "Bakersfield, CA", city: "Bakersfield", state: "California" },
  { name: "Fresno, CA", city: "Fresno", state: "California" },
  {
    name: "Los Angeles-Long Beach-Anaheim, CA",
    city: "Los Angeles-Long Beach-Anaheim",
    state: "California",
  },
  { name: "Riverside, CA", city: "Riverside", state: "California" },
  { name: "Sacramento, CA", city: "Sacramento", state: "California" },
  { name: "San Diego, CA", city: "San Diego", state: "California" },
  { name: "San Francisco, CA", city: "San Francisco", state: "California" },
  { name: "San Jose, CA", city: "San Jose", state: "California" },
  { name: "Ventura, CA", city: "Ventura", state: "California" },
  { name: "Colorado Springs, CO", city: "Colorado Springs", state: "Colorado" },
  { name: "Denver, CO", city: "Denver", state: "Colorado" },
  { name: "Fort Collins, CO", city: "Fort Collins", state: "Colorado" },
  { name: "Hartford, CT", city: "Hartford", state: "Connecticut" },
  { name: "New Haven, CT", city: "New Haven", state: "Connecticut" },
  { name: "Stamford, CT", city: "Stamford", state: "Connecticut" },
  { name: "Washington, DC", city: "Washington", state: "Washington, DC" },
  { name: "Daytona Beach, FL", city: "Daytona Beach", state: "Florida" },
  { name: "Fort Myers, FL", city: "Fort Myers", state: "Florida" },
  { name: "Jacksonville, FL", city: "Jacksonville", state: "Florida" },
  {
    name: "Miami-Fort Lauderdale, FL",
    city: "Miami-Fort Lauderdale",
    state: "Florida",
  },
  { name: "Tampa, FL", city: "Tampa", state: "Florida" },
  { name: "Atlanta, GA", city: "Atlanta", state: "Georgia" },
  { name: "Urban Honolulu, HI", city: "Urban Honolulu", state: "Hawaii" },
  { name: "Des Moines, IA", city: "Des Moines", state: "Iowa" },
  { name: "Boise City, ID", city: "Boise City", state: "Idaho" },
  { name: "Chicago, IL", city: "Chicago", state: "Illinois" },
  { name: "Indianapolis, IN", city: "Indianapolis", state: "Indianna" },
  {
    name: "Louisville-Jefferson County, KY",
    city: "Louisville-Jefferson County",
    state: "Kentucky",
  },
  { name: "Baton Rouge, LA", city: "Baton Rouge", state: "Louisiana" },
  { name: "New Orleans, LA", city: "New Orleans", state: "Louisiana" },
  { name: "Boston, MA", city: "Boston", state: "Massachusetts" },
  { name: "Springfield, MA", city: "Springfield", state: "Massachusetts" },
  { name: "Worcester, MA", city: "Worcester", state: "Massachusetts" },
  { name: "Baltimore, MD", city: "Baltimore", state: "Maryland" },
  { name: "Detroit, MI", city: "Detroit", state: "Michigan" },
  { name: "Grand Rapids, MI", city: "Grand Rapids", state: "Michigan" },
  {
    name: "Minneapolis-St Paul, MN",
    city: "Minneapolis-St Paul",
    state: "Minnesota",
  },
  { name: "Kansas City, MO", city: "Kansas City", state: "Missouri" },
  { name: "St. Louis, MO", city: "St. Louis", state: "Missouri" },
  { name: "Charlotte, NC", city: "Charlotte", state: "North Carolina" },
  { name: "Durham, NC", city: "Durham", state: "North Carolina" },
  { name: "Raleigh, NC", city: "Raleigh", state: "North Carolina" },
  { name: "Omaha, NE", city: "Omaha", state: "Nebraska" },
  { name: "Albuquerque, NM", city: "Albuquerque", state: "New Mexico" },
  { name: "Las Vegas, NV", city: "Las Vegas", state: "Nevada" },
  { name: "Buffalo, NY", city: "Buffalo", state: "New York" },
  { name: "New York, NY", city: "New York", state: "New York" },
  { name: "Rochester, NY", city: "Rochester", state: "New York" },
  { name: "Syracuse, NY", city: "Syracuse", state: "New York" },
  { name: "Akron, OH", city: "Akron", state: "Ohio" },
  { name: "Cincinnati, OH", city: "Cincinnati", state: "Ohio" },
  { name: "Cleveland, OH", city: "Cleveland", state: "Ohio" },
  { name: "Columbus, OH", city: "Columbus", state: "Ohio" },
  { name: "Dayton, OH", city: "Dayton", state: "Ohio" },
  { name: "Toledo, OH", city: "Toledo", state: "Ohio" },
  { name: "Oklahoma City, OK", city: "Oklahoma City", state: "Oklahoma" },
  { name: "Tulsa, OK", city: "Tulsa", state: "Oklahoma" },
  { name: "Portland, OR", city: "Portland", state: "Oregon" },
  { name: "Allentown, PA", city: "Allentown", state: "Pennsylvania" },
  { name: "Philadelphia, PA", city: "Philadelphia", state: "Pennsylvania" },
  { name: "Pittsburgh, PA", city: "Pittsburgh", state: "Pennsylvania" },
  { name: "Providence, RI", city: "Providence", state: "Rhode Island" },
  { name: "Charleston, SC", city: "Charleston", state: "Souther Carolina" },
  { name: "Columbia, SC", city: "Columbia", state: "Souther Carolina" },
  { name: "Greenville, SC", city: "Greenville", state: "Souther Carolina" },
  { name: "Knoxville, TN", city: "Knoxville", state: "Tennessee" },
  { name: "Memphis, TN", city: "Memphis", state: "Tennessee" },
  { name: "Nashville, TN", city: "Nashville", state: "Tennessee" },
  { name: "Austin, TX", city: "Austin", state: "Texas" },
  { name: "Dallas-Fort Worth, TX", city: "Dallas-Fort Worth", state: "Texas" },
  { name: "El Paso, TX", city: "El Paso", state: "Texas" },
  { name: "Houston, TX", city: "Houston", state: "Texas" },
  { name: "San Antonio, TX", city: "San Antonio", state: "Texas" },
  { name: "Ogden, UT", city: "Ogden", state: "Utah" },
  { name: "Provo, UT", city: "Provo", state: "Utah" },
  { name: "Salt Lake City, UT", city: "Salt Lake City", state: "Utah" },
  { name: "Richmond, VA", city: "Richmond", state: "Virginia" },
  { name: "Madison, WI", city: "Madison", state: "Wisconsin" },
  { name: "Milwaukee, WI", city: "Milwaukee", state: "Wisconsin" },
];
